apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: gdalinfo-workflow
  annotations:
    workflows.argoproj.io/description: "Fetches basic metadata for a GeoTIFF URL using gdalinfo."
spec:
  entrypoint: process-geotiff
  arguments:
    parameters:
    - name: image-url
      value: "https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/36/Q/WD/2020/7/S2A_36QWD_20200701_0_L2A/B04.tif"
  
  templates:
  - name: process-geotiff
    steps:
    - - name: get-info
        template: gdalinfo
        arguments:
          parameters:
          - name: url
            value: "{{workflow.parameters.image-url}}"
    
  - name: gdalinfo
    inputs:
      parameters:
      - name: url
    container:
      image: ghcr.io/osgeo/gdal:ubuntu-small-3.9.0
      command: [gdalinfo]
      args: ["/vsicurl/{{inputs.parameters.url}}"]
